# Generated by Django 4.2.11 on 2024-11-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=10)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('phoneNumber', models.TextField(default='0000000000')),
            ],
        ),
    ]
