# Generated by Django 4.2.11 on 2024-11-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registerClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkbox', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('home', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=30)),
                ('stateClass', models.CharField(max_length=20)),
            ],
        ),
    ]
